import os

LEADERBOARD_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "leaderboard.json")

# -----------------------------
# STOCK CATEGORIES
# -----------------------------

STOCK_CATEGORIES = {
    "AI": {
        "NVIDIA":           "NVDA",
        "AMD":              "AMD",
        "Palantir":         "PLTR",
        "C3.ai":            "AI",
        "Super Micro":      "SMCI",
        "Arm Holdings":     "ARM",
        "SoundHound":       "SOUN",
    },
    "Technology": {
        "Apple":            "AAPL",
        "Microsoft":        "MSFT",
        "Google":           "GOOGL",
        "Meta":             "META",
        "Netflix":          "NFLX",
        "Oracle":           "ORCL",
        "IBM":              "IBM",
        "Qualcomm":         "QCOM",
        "Intel":            "INTC",
        "Salesforce":       "CRM",
        "Snowflake":        "SNOW",
        "Zoom":             "ZM",
    },
    "Energy": {
        "ExxonMobil":       "XOM",
        "Chevron":          "CVX",
        "Shell":            "SHEL",
        "BP":               "BP",
        "ConocoPhillips":   "COP",
        "NextEra":          "NEE",
        "Enphase":          "ENPH",
        "SolarEdge":        "SEDG",
        "Schlumberger":     "SLB",
    },
    "Finance": {
        "JPMorgan":         "JPM",
        "Goldman Sachs":    "GS",
        "Bank of America":  "BAC",
        "Morgan Stanley":   "MS",
        "Visa":             "V",
        "Mastercard":       "MA",
        "Berkshire":        "BRK-B",
        "BlackRock":        "BLK",
        "Charles Schwab":   "SCHW",
        "Coinbase":         "COIN",
        "PayPal":           "PYPL",
        "Robinhood":        "HOOD",
    },
    "Healthcare": {
        "Johnson & Johnson":"JNJ",
        "Pfizer":           "PFE",
        "UnitedHealth":     "UNH",
        "Moderna":          "MRNA",
        "Eli Lilly":        "LLY",
        "Merck":            "MRK",
        "AbbVie":           "ABBV",
        "Intuitive Surgical":"ISRG",
    },
    "Retail": {
        "Amazon":           "AMZN",
        "Walmart":          "WMT",
        "Costco":           "COST",
        "Target":           "TGT",
        "McDonald's":       "MCD",
        "Starbucks":        "SBUX",
        "Nike":             "NKE",
        "Home Depot":       "HD",
        "eBay":             "EBAY",
    },
    "Automotive": {
        "Tesla":            "TSLA",
        "Ford":             "F",
        "GM":               "GM",
        "Rivian":           "RIVN",
        "Lucid":            "LCID",
        "Ferrari":          "RACE",
    },
    "Defense": {
        "Lockheed Martin":  "LMT",
        "Boeing":           "BA",
        "Raytheon":         "RTX",
        "Northrop Grumman": "NOC",
        "General Dynamics": "GD",
        "L3Harris":         "LHX",
    },
    "Entertainment": {
        "Disney":           "DIS",
        "Spotify":          "SPOT",
        "Roblox":           "RBLX",
        "Warner Bros":      "WBD",
        "Live Nation":      "LYV",
        "Electronic Arts":  "EA",
        "Take-Two":         "TTWO",
    },
    "Space": {
        "Rocket Lab":       "RKLB",
        "Virgin Galactic":  "SPCE",
        "Intuitive Machines":"LUNR",
        "Redwire":          "RDW",
    },
}

CATEGORY_PRICE_RANGES = {
    "AI":           (50,  800),
    "Technology":   (50,  500),
    "Energy":       (20,  200),
    "Finance":      (30,  500),
    "Healthcare":   (50,  600),
    "Retail":       (20,  400),
    "Automotive":   (5,   300),
    "Defense":      (100, 600),
    "Entertainment":(10,  200),
    "Space":        (2,   50),
    "Custom":       (10,  500),
}
